name: CI
on:
  pull_request:
env:
  ALIASES: ${{ vars.ALIASES }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Get deployment alias
        run: node scripts/githubActions.mjs getAlias
        id: alias
      - run: echo $OUTPUT
        env:
          OUTPUT: ${{ steps.alias.outputs.alias }}
